name: test

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: mxschmitt/action-tmate@v3
    - name: composer
      run: composer update --no-dev -o 
    - name: test
      run: |
        bin/arche-create-metadata-template /tmp all
        RET=1
        bin/arche-crawl-meta tests/meta/ /tmp/metadata.ttl /home/zozlak/roboty/ACDH/repo/metadata-crawler/tests/data https://id.acdh.oeaw.ac.at/tests || RET=0
        exit $RET

